### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by official-notfishvr** [thedogecraft/dotline#16]
<img width="630" height="660" alt="Image" src="https://github.com/user-attachments/assets/7f5d7343-43a5-442f-99a4-149b7beb524c" />

every time i open the app it says this

**Comment by tabbi-dev** [comment]
I get a similar error on Linux after updating to 4.0, even after building from source.
Here is the output when launching:
```
tabbi ~/git/dotline/dist (main)> ./dotline-0.4.0.AppImage
(node:33350) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `dotline --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'ms'
Require stack:
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/debug/src/common.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/debug/src/node.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/debug/src/index.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/builder-util-runtime/out/index.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/node_modules/electron-updater/out/main.js
- /tmp/.mount_dotlinjBndUk/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1483:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:140587)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1056:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1080:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1101:12)
    at Module._load (node:internal/modules/cjs/loader:1269:25)
    at c._load (node:electron/js2c/node_init:2:18060)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1583:12)
    at require (node:internal/modules/helpers:153:16)
[33392:0525/183812.570074:ERROR:ui/ozone/platform/wayland/gpu/wayland_surface_factory.cc:251] '--ozone-platform=wayland' is not compatible with Vulkan. Consider switching to '--ozone-platform=x11' or disabling Vulkan
```

The process then hangs until I manually kill it.

**Comment by FuelClock** [comment]
Similar error on my end when using the AppImage with Linux CachyOS, KDE Plasma on wayland,
And also hangs until process is manually killed.

```
❯ ./dotline-0.4.0.AppImage 
(node:9316) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `dotline --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'ms'
Require stack:
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/debug/src/common.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/debug/src/node.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/debug/src/index.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/builder-util-runtime/out/index.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/node_modules/electron-updater/out/main.js
- /tmp/.mount_dotlinoVMnkW/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1483:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:140587)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1056:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1080:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1101:12)
    at Module._load (node:internal/modules/cjs/loader:1269:25)
    at c._load (node:electron/js2c/node_init:2:18060)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1583:12)
    at require (node:internal/modules/helpers:153:16)
```
